---
name: On master branch, tag and then, publish to ansible-galaxy

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to ansible galaxy

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests

      - name: Bump version and push tag
        id: set_version
        uses: anothrNick/github-tag-action@1b82315fa74a0572aa0bc1a96b859c57fc26e531
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: patch

      - name: Push to ansible galaxy
        run: |
          ansible-galaxy role import \
            --api-key ${{ secrets.GALAXY_API_KEY }} \
            --role-name $(echo ${{ github.repository }} | cut -d/ -f2 | sed -e 's/ansible-role-//g') \
            $(echo ${{ github.repository }} | cut -d/ -f1) \
            $(echo ${{ github.repository }} | cut -d/ -f2)
